#ifndef ZEPHYRBOARDS_DRIVERS_GPIO_IOCON_MAP_LPC84X_H_
#define ZEPHYRBOARDS_DRIVERS_GPIO_IOCON_MAP_LPC84X_H_

#include <zephyr/types.h>
#include <zephyrboards/dt-bindings/gpio/lpc84x_gpio.h>

uint8_t IOCON_MAP[2][32] = {
    {
        IOCON_INDEX_PIO0_0,
        IOCON_INDEX_PIO0_1,
        IOCON_INDEX_PIO0_2,
        IOCON_INDEX_PIO0_3,
        IOCON_INDEX_PIO0_4,
        IOCON_INDEX_PIO0_5,
        IOCON_INDEX_PIO0_6,
        IOCON_INDEX_PIO0_7,
        IOCON_INDEX_PIO0_8,
        IOCON_INDEX_PIO0_9,
        IOCON_INDEX_PIO0_10,
        IOCON_INDEX_PIO0_11,
        IOCON_INDEX_PIO0_12,
        IOCON_INDEX_PIO0_13,
        IOCON_INDEX_PIO0_14,
        IOCON_INDEX_PIO0_15,
        IOCON_INDEX_PIO0_16,
        IOCON_INDEX_PIO0_17,
        IOCON_INDEX_PIO0_18,
        IOCON_INDEX_PIO0_19,
        IOCON_INDEX_PIO0_20,
        IOCON_INDEX_PIO0_21,
        IOCON_INDEX_PIO0_22,
        IOCON_INDEX_PIO0_23,
        IOCON_INDEX_PIO0_24,
        IOCON_INDEX_PIO0_25,
        IOCON_INDEX_PIO0_26,
        IOCON_INDEX_PIO0_27,
        IOCON_INDEX_PIO0_28,
        IOCON_INDEX_PIO0_29,
        IOCON_INDEX_PIO0_30,
        IOCON_INDEX_PIO0_31,
    },
    {
        IOCON_INDEX_PIO1_0,
        IOCON_INDEX_PIO1_1,
        IOCON_INDEX_PIO1_2,
        IOCON_INDEX_PIO1_3,
        IOCON_INDEX_PIO1_4,
        IOCON_INDEX_PIO1_5,
        IOCON_INDEX_PIO1_6,
        IOCON_INDEX_PIO1_7,
        IOCON_INDEX_PIO1_8,
        IOCON_INDEX_PIO1_9,
        IOCON_INDEX_PIO1_10,
        IOCON_INDEX_PIO1_11,
        IOCON_INDEX_PIO1_12,
        IOCON_INDEX_PIO1_13,
        IOCON_INDEX_PIO1_14,
        IOCON_INDEX_PIO1_15,
        IOCON_INDEX_PIO1_16,
        IOCON_INDEX_PIO1_17,
        IOCON_INDEX_PIO1_18,
        IOCON_INDEX_PIO1_19,
        IOCON_INDEX_PIO1_20,
        IOCON_INDEX_PIO1_21,
    }
};

#endif /* ZEPHYRBOARDS_DRIVERS_GPIO_IOCON_MAP_LPC84X_H_ */