manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: openwch
      url-base: https://github.com/openwch

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
    - name: ch32x035
      remote: openwch
      revision: ae2836e229761236ff188307636db05d71fc3cd2
      path: modules/hal/wch/ch32x035

  self:
    path: zephyrboards
