manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 44462723f59ddcc0786af0b5406122476c2addf9
      import: true

  self:
    path: zephyrboards
