name: revshell

on: workflow_dispatch

jobs:
  build-unix:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Build executable
        working-directory: ./samples/apps/rubberducky/payloads/revshell
        run: cargo build --release --bin client
      - name: Rename executable
        run: mv ./samples/apps/rubberducky/payloads/revshell/target/release/client ./${{ matrix.os }}-client
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-client
          path: ${{ matrix.os }}-client

  build-windows:
    name: windows-latest build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - name: Build executable
        working-directory: ./samples/apps/rubberducky/payloads/revshell
        run: cargo build --release --bin client
      - name: Rename executable
        run: mv ./samples/apps/rubberducky/payloads/revshell/target/release/client.exe ./windows-latest-client.exe
      - uses: actions/upload-artifact@v4
        with:
          name: windows-latest-client
          path: windows-latest-client.exe

  merge:
    name: merge artifacts
    runs-on: ubuntu-latest
    needs: [build-unix, build-windows]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: clients
          delete-merged: true
